id: A04F44347
base_file: fF1FF.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 14:03:38.380093
  last_modified_at: 2022-06-17 14:03:38.380103
