id: A04F44347
base_file: fDFDE.txt
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-06-17 14:03:38.377417
  last_modified_at: 2022-06-17 14:03:38.377424
