id: A04F44347
base_file: f4EA5.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 14:03:38.362113
  last_modified_at: 2022-06-17 14:03:38.362134
